import {enabled} from "../helpers.js";

const SOURCE_ITEMS = [
  {title: "HDHive", value: "hdhive"},
  {title: "Dian115", value: "dian115"},
  {title: "PanSou", value: "pansou"},
  {title: "聚影", value: "juying"},
  {title: "盘链", value: "pinglian"},
  {title: "SeedHub", value: "seedhub"},
  {title: "海盗湾", value: "piratebay"},
  {title: "UIndex", value: "uindex"},
  {title: "Mikan", value: "mikan"},
  {title: "AnimeGarden", value: "animegarden"},
  {title: "在线文档", value: "online_docs"},
]

export function createCommonSearchGroups(resourceTypeItems) {
  return [
    {
      tab: "common",
      title: "搜索顺序",
      icon: "mdi-sort",
      hint: "按勾选顺序设置搜索源优先级；未选择的搜索源不会发起请求。",
      fields: [
        {
          key: "search_source_order",
          label: "搜索资源优先级",
          hint: "点击打开配置窗口，通过拖拽卡片调整搜索源查询优先级（排在前面的最高优先）；留空时不限制搜索渠道。",
          type: "priority-order",
          items: SOURCE_ITEMS,
          cols: 12,
        },
        {
          key: "resource_type_order",
          label: "资源类型优先级",
          hint: "点击打开配置窗口，通过拖拽卡片调整网盘与资源类型匹配优先级（排在前面的优先选择与下载）。",
          type: "priority-order",
          items: resourceTypeItems,
          cols: 12,
        },
        {
          key: "magnet_metadata_url_template",
          label: "Magnet元数据地址模板",
          hint: "必须包含 {info_hash}；返回内容会由torf解码并校验Info Hash。",
          placeholder: "https://itorrents.org/torrent/{info_hash}.torrent",
          cols: 12,
        },
      ],
    },
    {
      tab: "common",
      title: "搜索代理",
      icon: "mdi-lan-connect",
      hint: "仅代理搜索渠道请求；测试使用 Cloudflare Trace 获取请求延迟、出口 IP、地区和节点。",
      fields: [
        {
          key: "search_proxy",
          label: "代理地址",
          type: "proxy",
          hint: "支持 http://、https://、socks5:// 和 host:port，留空则直连。",
          placeholder: "http://127.0.0.1:7890",
          cols: 12,
        },
        {
          key: "search_proxy_username",
          label: "代理用户名",
          cols: 6,
        },
        {
          key: "search_proxy_password",
          label: "代理密码",
          type: "password",
          cols: 6,
        },
      ],
    },
    {
      tab: "common",
      title: "搜索性能",
      icon: "mdi-speedometer",
      hint: "控制跨搜索源查询并发、超时与本地缓存；115接口与积分解锁仍保持串行限速。",
      fields: [
        {
          key: "search_concurrency",
          label: "搜索并发数",
          hint: "跨渠道并发查询数（1 为逐源查询，建议 2，最大 5）",
          type: "number",
          min: 1,
          max: 5,
          cols: 6,
        },
        {
          key: "search_source_timeout",
          label: "搜索超时",
          hint: "未单独配置超时的搜索源默认最长等待时间，默认 60 秒",
          type: "number",
          min: 5,
          max: 120,
          suffix: "秒",
          cols: 6,
        },
        {
          key: "search_cache_enabled",
          label: "启用搜索缓存",
          hint: "缓存搜索源查询结果，避免重复检索相同内容",
          type: "switch",
          cols: 6,
        },
        {
          key: "search_cache_ttl_minutes",
          label: "缓存时间（分钟）",
          hint: "搜索结果本地缓存有效期，默认 30 分钟",
          type: "number",
          min: 1,
          max: 1440,
          cols: 6,
          show: enabled("search_cache_enabled"),
        },
      ],
    },
    {
      tab: "common",
      title: "故障熔断",
      icon: "mdi-shield-alert-outline",
      hint: "渠道连续请求失败或超时时自动熔断降级，避免连锁阻塞后续任务。",
      fields: [
        {
          key: "search_circuit_breaker_enabled",
          label: "启用故障熔断机制",
          hint: "渠道连续故障时自动跳过，期满自动探测恢复",
          type: "switch",
          cols: 4,
        },
        {
          key: "search_circuit_breaker_threshold",
          label: "连续失败熔断阈值",
          hint: "连续失败或超时达到此次数后触发熔断",
          type: "number",
          min: 1,
          max: 10,
          suffix: "次",
          cols: 4,
          show: enabled("search_circuit_breaker_enabled"),
        },
        {
          key: "search_circuit_breaker_cooldown",
          label: "熔断冷却时间",
          hint: "触发熔断后跳过该渠道的时间，期满自动试探恢复",
          type: "number",
          min: 10,
          max: 600,
          suffix: "秒",
          cols: 4,
          show: enabled("search_circuit_breaker_enabled"),
        },
      ],
    },
  ]
}
