export function createDian115Groups(options = {}) {
  return [
    {
      tab: "dian115",
      title: "Dian115 账号",
      icon: "mdi-account-key-outline",
      hint: "使用浏览器仿真完成 Turnstile 登录并维护访问状态。",
      fields: [
        {
          key: "dian115_account_info",
          type: "account",
          accountKey: "search:dian115",
          data: options.searchAccounts?.dian115 || {},
          compact: true,
          cols: 12,
        },
        {
          key: "dian115_base_url",
          label: "服务地址",
          cols: 12,
        },
        {
          key: "dian115_email",
          label: "登录邮箱",
          cols: 6,
        },
        {
          key: "dian115_password",
          label: "登录密码",
          type: "password",
          cols: 6,
        },
        {
          key: "test_dian115",
          label: "测试搜索",
          type: "test-source",
          source: "dian115",
          cols: 12,
        },
      ],
    },
    {
      tab: "dian115",
      title: "Dian115 积分解锁",
      icon: "mdi-ticket-confirmation-outline",
      fields: [
        {
          key: "dian115_auto_unlock",
          label: "允许积分解锁",
          type: "switch",
          cols: 4,
        },
        {
          key: "dian115_max_unlock_points",
          label: "单次积分总预算",
          hint: "单次同步最大解锁积分",
          type: "number",
          min: 0,
          cols: 4,
          show: (config) => config.dian115_auto_unlock,
        },
        {
          key: "dian115_max_points_per_sub",
          label: "单订阅解锁预算",
          hint: "单订阅累计解锁预算",
          type: "number",
          min: 0,
          cols: 4,
          show: (config) => config.dian115_auto_unlock,
        },
      ],
    },
    {
      tab: "dian115",
      title: "搜索与风控",
      icon: "mdi-shield-search",
      fields: [
        {
          key: "dian115_candidate_limit",
          label: "候选上限",
          hint: "最大保留候选数量",
          type: "number",
          min: 1,
          max: 20,
          cols: 3,
        },
        {
          key: "dian115_unlocks_per_minute",
          label: "每分钟解锁次数",
          hint: "解锁频次限制，默认 6 次",
          type: "number",
          min: 1,
          max: 10,
          suffix: "次",
          cols: 3,
        },
        {
          key: "dian115_request_interval",
          label: "请求间隔",
          hint: "接口请求基础间隔秒数",
          type: "number",
          min: 0.2,
          max: 10,
          step: 0.2,
          suffix: "秒",
          cols: 3,
        },
        {
          key: "dian115_timeout",
          label: "搜索超时",
          hint: "单次搜索超时秒数，默认 60 秒",
          type: "number",
          min: 5,
          max: 120,
          suffix: "秒",
          cols: 3,
        },
      ],
    },
  ]
}
