import {enabled} from "../helpers.js";

export function createHdhiveGroups(options = {}) {
  return [
    {
      tab: "hdhive",
      title: "HDHive 接入",
      icon: "mdi-hexagon-multiple-outline",
      hint: "默认使用功能完整的 WebAPI；OpenAPI 适合已申请应用并完成 OAuth 用户授权的场景。",
      fields: [
        {
          key: "hdhive_account_info",
          type: "account",
          accountKey: "search:hdhive",
          data: options.searchAccounts?.hdhive || {},
          compact: true,
          cols: 12,
        },
        {
          key: "hdhive_base_url",
          label: "服务地址",
          cols: 12,
          show: (config) => config.hdhive_query_mode === "web",
        },
        {
          key: "hdhive_query_mode",
          label: "查询模式",
          type: "select",
          items: [
            { title: "WebAPI", value: "web" },
            { title: "OpenAPI", value: "api" },
          ],
          cols: 4,
        },
        {
          key: "hdhive_api_key",
          label: "API Key / 应用 Secret",
          type: "password",
          cols: 4,
          show: (config) => config.hdhive_query_mode === "api",
        },
        {
          key: "hdhive_client_id",
          label: "Client ID",
          cols: 4,
          show: (config) => config.hdhive_query_mode === "api",
        },
        {
          key: "hdhive_redirect_uri",
          label: "OAuth Redirect URI",
          hint: "必须与 HDHive OpenAPI 应用配置完全一致，且不能包含 fragment。",
          cols: 6,
          show: (config) => config.hdhive_query_mode === "api",
        },
        {
          key: "hdhive_response_mode",
          label: "OAuth 回调模式",
          type: "select",
          items: [
            { title: "Redirect（复制回调 URL）", value: "redirect" },
            { title: "PostMessage（弹窗自动回传）", value: "postmessage" },
          ],
          cols: 6,
          show: (config) => config.hdhive_query_mode === "api",
        },
        {
          key: "hdhive_oauth",
          type: "hdhive-oauth",
          cols: 12,
          show: (config) => config.hdhive_query_mode === "api",
        },
        {
          key: "hdhive_access_token",
          label: "Access Token",
          type: "password",
          cols: 6,
          show: (config) => config.hdhive_query_mode === "api",
        },
        {
          key: "hdhive_refresh_token",
          label: "Refresh Token",
          type: "password",
          cols: 6,
          show: (config) => config.hdhive_query_mode === "api",
        },
        {
          key: "hdhive_username",
          label: "HDHive 用户名",
          cols: 4,
          show: (config) => config.hdhive_query_mode === "web",
        },
        {
          key: "hdhive_password",
          label: "HDHive 密码",
          type: "password",
          cols: 4,
          show: (config) => config.hdhive_query_mode === "web",
        },
        {
          key: "test_hdhive",
          label: "测试搜索",
          type: "test-source",
          source: "hdhive",
          cols: 12,
        },
      ],
    },
    {
      tab: "hdhive",
      title: "HDHive 积分解锁",
      icon: "mdi-ticket-confirmation-outline",
      fields: [
        {
          key: "hdhive_auto_unlock",
          label: "允许积分解锁",
          type: "switch",
          cols: 4,
        },
        {
          key: "hdhive_max_unlock_points",
          label: "单次积分总预算",
          hint: "单次同步最大解锁积分",
          type: "number",
          min: 0,
          cols: 4,
          show: (config) => config.hdhive_auto_unlock,
        },
        {
          key: "hdhive_max_points_per_sub",
          label: "单订阅解锁预算",
          hint: "单订阅累计解锁预算",
          type: "number",
          min: 0,
          cols: 4,
          show: (config) => config.hdhive_auto_unlock,
        },
      ],
    },
    {
      tab: "hdhive",
      title: "搜索与风控",
      icon: "mdi-shield-search",
      fields: [
        {
          key: "hdhive_candidate_limit",
          label: "候选上限",
          hint: "最大保留候选数量",
          type: "number",
          min: 1,
          max: 20,
          cols: 3,
        },
        {
          key: "hdhive_timeout",
          label: "搜索超时",
          hint: "单次搜索超时秒数，默认 60 秒",
          type: "number",
          min: 5,
          max: 120,
          suffix: "秒",
          cols: 3,
        },
        {
          key: "hdhive_request_interval",
          label: "请求访问间隔",
          hint: "接口请求基础间隔秒数",
          type: "number",
          min: 2,
          max: 10,
          step: 0.5,
          suffix: "秒",
          cols: 3,
        },
        {
          key: "hdhive_unlocks_per_minute",
          label: "每分钟解锁次数",
          hint: "WebAPI 解锁频次限制，默认 2 次",
          type: "number",
          min: 1,
          max: 5,
          step: 1,
          suffix: "次/分钟",
          cols: 3,
          show: (config) => config.hdhive_query_mode === "web",
        },
        {
          key: "hdhive_torrentclaw_enabled",
          label: "获取 TorrentClaw Magnet",
          hint: "按优先级获取磁力资源",
          type: "switch",
          cols: 12,
          show: (config) => config.hdhive_query_mode === "web",
        },
        {
          key: "hdhive_torrentclaw_subtitle_languages",
          label: "Magnet字幕语言筛选",
          hint: "优先匹配所选字幕语言，默认中文",
          type: "select",
          items: [
            { title: "中文", value: "zh" },
            { title: "英语", value: "en" },
            { title: "日语", value: "ja" },
            { title: "韩语", value: "ko" },
            { title: "葡萄牙语（巴西）", value: "pt-BR" },
            { title: "葡萄牙语（葡萄牙）", value: "pt-PT" },
            { title: "西班牙语", value: "es" },
            { title: "法语", value: "fr" },
            { title: "德语", value: "de" },
            { title: "意大利语", value: "it" },
            { title: "俄语", value: "ru" },
            { title: "阿拉伯语", value: "ar" },
            { title: "泰语", value: "th" },
            { title: "土耳其语", value: "tr" },
            { title: "印地语", value: "hi" },
            { title: "泰米尔语", value: "ta" },
            { title: "泰卢固语", value: "te" },
          ],
          multiple: true,
          cols: 12,
          show: (config) => config.hdhive_query_mode === "web" && enabled("hdhive_torrentclaw_enabled")(config),
        },
      ],
    },
  ]
}
