export function createMikanGroups() {
  const fansubPresets = [
    {title: "LoliHouse", value: "LoliHouse"},
    {title: "VCB-Studio", value: "VCB-Studio"},
    {title: "喵萌奶茶屋", value: "喵萌奶茶|Nekomoe"},
    {title: "Nix-Raws", value: "Nix-Raws"},
    {title: "ANI", value: "\\bANI\\b|ANi"},
    {title: "SweetSub", value: "SweetSub"},
    {title: "千夏字幕组", value: "千夏"},
    {title: "动漫国字幕组", value: "动漫国|動漫國|DMG"},
    {title: "极影字幕社", value: "极影|極影|KTXP"},
    {title: "樱都字幕组", value: "桜都|樱都|櫻都|Sakurato"},
    {title: "诸神字幕组", value: "诸神|諸神|Kamigami"},
    {title: "北宇治字幕组", value: "北宇治|Kitauji"},
    {title: "悠哈璃羽字幕社", value: "悠哈璃羽|UHA-WINGS"},
    {title: "爱恋字幕社", value: "爱恋字幕|愛戀字幕|KissSub"},
    {title: "拨雪寻春", value: "拨雪寻春|撥雪尋春"},
    {title: "HaruHana", value: "Haru[ &]+Hana"},
    {title: "澄空学园", value: "澄空|Sumisora"},
    {title: "华盟字幕社", value: "华盟|華盟|CASO"},
    {title: "霜庭云花", value: "霜庭云花|霜庭雲花|STYH"},
    {title: "豌豆字幕组", value: "豌豆|Dymy"},
    {title: "Airota", value: "Airota"},
    {title: "Lilith-Raws", value: "Lilith-Raws"},
    {title: "DBD制作组", value: "DBD制作组|DBD-Raws"},
    {title: "NC-Raws", value: "\\bNC-Raws\\b"},
    {title: "雪飘工作室", value: "雪飘|FLsnow"},
    {title: "幻樱字幕组", value: "幻樱|HYSub"},
  ];

  return [
    {
      tab: "mikan",
      title: "Mikan",
      icon: "mdi-animation-play-outline",
      fields: [
        {
          key: "mikan_base_url",
          label: "接口/镜像地址",
          hint: "默认官方地址，支持自定义镜像",
          cols: 12,
        },
        {
          key: "mikan_fansub_order",
          label: "字幕组优先级偏好",
          type: "priority-order",
          cols: 12,
          items: fansubPresets,
          allowCustom: true,
          default: ["LoliHouse", "VCB-Studio", "喵萌奶茶|Nekomoe", "Nix-Raws", "\\bANI\\b|ANi"],
          hint: "按优先级排序字幕组，支持拖拽调序",
        },
        {
          key: "mikan_exclude_re",
          label: "动漫排除正则",
          type: "text",
          placeholder: "720[pP]|480[pP]|特别篇|特別篇|\\b(?:SP|OVA|OAD)\\d*|\\b\\d+\\s*-\\s*\\d+\\b",
          hint: "过滤不需要的动漫资源，留空使用默认",
          cols: 12,
        },
        {
          key: "mikan_no_subs_re",
          label: "生肉/无字幕排除正则",
          type: "text",
          placeholder: "无字幕|無字幕|无字版|無字版|生肉|\\b(?:unsubbed|no[ ._-]*subs?|subtitle[ ._-]*free)\\b",
          hint: "生肉排除正则，留空使用默认",
          cols: 12,
        },
        {
          key: "mikan_chinese_re",
          label: "中文字幕匹配正则",
          type: "text",
          placeholder: "简[体體繁中]|簡[体體繁中]|繁[体體简簡中]|中[日英双雙文]|[简簡繁]日|\\b(?:CHS|CHT|BIG5|GB|SC|TC|ZH|CHI|ZHO)(?:\\b|_)",
          hint: "中文字幕匹配正则，留空使用默认",
          cols: 12,
        },

        {
          key: "test_mikan",
          label: "测试搜索",
          type: "test-source",
          source: "mikan",
          cols: 12,
        },
      ],
    },
    {
      tab: "mikan",
      title: "搜索与限速",
      icon: "mdi-shield-search",
      fields: [
        {
          key: "mikan_result_limit",
          label: "候选上限",
          type: "number",
          min: 1,
          max: 200,
          cols: 4,
        },
        {
          key: "mikan_request_interval",
          label: "请求间隔",
          type: "number",
          min: 0.2,
          max: 10,
          step: 0.1,
          suffix: "秒",
          cols: 4,
        },
        {
          key: "mikan_timeout",
          label: "搜索超时",
          type: "number",
          min: 5,
          max: 120,
          suffix: "秒",
          cols: 4,
        },
      ],
    },
  ];
}
