const netflixCountries = {
  AE: "United Arab Emirates",
  AR: "Argentina",
  AT: "Austria",
  AU: "Australia",
  BD: "Bangladesh",
  BE: "Belgium",
  BG: "Bulgaria",
  BH: "Bahrain",
  BO: "Bolivia",
  BR: "Brazil",
  BS: "Bahamas",
  CA: "Canada",
  CH: "Switzerland",
  CL: "Chile",
  CO: "Colombia",
  CR: "Costa Rica",
  CY: "Cyprus",
  CZ: "Czech Republic",
  DE: "Germany",
  DK: "Denmark",
  DO: "Dominican Republic",
  EC: "Ecuador",
  EE: "Estonia",
  EG: "Egypt",
  ES: "Spain",
  FI: "Finland",
  FR: "France",
  GB: "United Kingdom",
  GP: "Guadeloupe",
  GR: "Greece",
  GT: "Guatemala",
  HK: "Hong Kong",
  HN: "Honduras",
  HR: "Croatia",
  HU: "Hungary",
  ID: "Indonesia",
  IE: "Ireland",
  IL: "Israel",
  IN: "India",
  IS: "Iceland",
  IT: "Italy",
  JM: "Jamaica",
  JO: "Jordan",
  JP: "Japan",
  KE: "Kenya",
  KR: "South Korea",
  KW: "Kuwait",
  LB: "Lebanon",
  LK: "Sri Lanka",
  LT: "Lithuania",
  LU: "Luxembourg",
  LV: "Latvia",
  MA: "Morocco",
  MQ: "Martinique",
  MT: "Malta",
  MU: "Mauritius",
  MV: "Maldives",
  MX: "Mexico",
  MY: "Malaysia",
  NC: "New Caledonia",
  NG: "Nigeria",
  NI: "Nicaragua",
  NL: "Netherlands",
  NO: "Norway",
  NZ: "New Zealand",
  OM: "Oman",
  PA: "Panama",
  PE: "Peru",
  PH: "Philippines",
  PK: "Pakistan",
  PL: "Poland",
  PT: "Portugal",
  PY: "Paraguay",
  QA: "Qatar",
  RE: "Réunion",
  RO: "Romania",
  RS: "Serbia",
  RU: "Russia",
  SA: "Saudi Arabia",
  SE: "Sweden",
  SG: "Singapore",
  SI: "Slovenia",
  SK: "Slovakia",
  SV: "El Salvador",
  TH: "Thailand",
  TR: "Turkey",
  TT: "Trinidad and Tobago",
  TW: "Taiwan",
  UA: "Ukraine",
  US: "United States",
  UY: "Uruguay",
  VE: "Venezuela",
  VN: "Vietnam",
  ZA: "South Africa",
};
const netflixCountryItems = Object.entries(netflixCountries).map(([value, title]) => ({title, value}));

export function createSubscribeSection(options = {}) {
  return {
    value: "auto_subscribe",
    title: "榜单订阅",
    icon: "mdi-format-list-bulleted-square",
    subtabs: [
      {value: "global", title: "通用", icon: "mdi-tune-variant"},
      {value: "douban", title: "豆瓣", icon: "mdi-star-outline"},
      {value: "maoyan", title: "猫眼", icon: "mdi-filmstrip"},
      {value: "netflix", title: "Netflix", icon: "mdi-netflix"},
      {value: "mikan", title: "Mikan", icon: "mdi-animation-outline"},
    ],
    groups: [
      {
        title: "通用规则",
        icon: "mdi-filter-cog-outline",
        tab: "global",
        fields: [
          {key: "auto_subscribe_enabled", label: "启用榜单自动订阅", type: "switch", cols: 4},
          {
            key: "auto_subscribe_onlyonce",
            label: "保存后立即运行一次",
            type: "switch",
            hint: "保存后运行所有已启用榜单一次，随后自动复位。",
            cols: 4,
          },
          {key: "auto_subscribe_notify", label: "发送运行结果通知", type: "switch", cols: 4},
          {
            key: "auto_subscribe_cron",
            label: "榜单订阅执行周期",
            type: "cron",
            hint: "所有已启用榜单按此周期并发抓取。",
            cols: 12,
          },
          {
            key: "auto_subscribe_skip_season_zero",
            label: "跳过第 0 季",
            type: "switch",
            hint: "只影响季号为 Season 0 的特别篇，不会阻止正常季度订阅。",
            cols: 4,
          },
          {key: "auto_subscribe_skip_subscribed", label: "跳过已有活动订阅", type: "switch", cols: 4},
          {key: "auto_subscribe_skip_history", label: "跳过历史订阅", type: "switch", cols: 4},
          {key: "auto_subscribe_skip_library", label: "跳过媒体库已有内容", type: "switch", cols: 4},
          {
            key: "auto_subscribe_username",
            label: "订阅用户名",
            hint: "写入 MoviePilot 订阅记录，用于通知、归属和历史展示。",
            cols: 12,
          },
        ],
      },
      {
        title: "代理服务器",
        icon: "mdi-lan-connect",
        tab: "global",
        hint: "统一配置榜单请求代理；各榜单可在自己的连接分组中决定是否启用。",
        fields: [
          {
            key: "auto_subscribe_proxy",
            label: "代理地址",
            type: "auto-subscribe-proxy",
            hint: "支持 http://、https://、socks5:// 和 host:port，留空则直连。",
            placeholder: "http://127.0.0.1:7890",
            cols: 12,
          },
          {key: "auto_subscribe_proxy_username", label: "代理用户名", cols: 6},
          {key: "auto_subscribe_proxy_password", label: "代理密码", type: "password", cols: 6},
        ],
      },
      {
        title: "豆瓣连接与测试",
        icon: "mdi-server-network-outline",
        tab: "douban",
        fields: [
          {key: "auto_subscribe_douban_enabled", label: "启用豆瓣榜单", type: "switch", cols: 6},
          {
            key: "auto_subscribe_douban_proxy",
            label: "启用代理服务器",
            type: "switch",
            hint: "使用通用设置中的榜单代理。",
            cols: 6,
          },
          {
            key: "auto_subscribe_douban_rsshub_base",
            label: "RSSHub 服务地址",
            type: "combobox",
            multiple: false,
            items: options.rsshubInstances || [],
            loading: options.rsshubLoading,
            hint: "可选择公告页中的公共实例，也可直接输入自建地址。",
            cols: 12,
          },
          {
            key: "auto_subscribe_douban_test",
            label: "测试豆瓣榜单",
            type: "test-auto-subscribe",
            provider: "douban",
            cols: 12,
          },
        ],
      },
      {
        title: "豆瓣榜单范围",
        icon: "mdi-star-outline",
        tab: "douban",
        fields: [
          {
            key: "auto_subscribe_douban_ranks",
            label: "热门榜单",
            type: "select",
            multiple: true,
            items: [
              {title: "电影北美票房榜", value: "movie-ustop"},
              {title: "一周口碑电影榜", value: "movie-weekly"},
              {title: "实时热门电影", value: "movie-real-time"},
              {title: "热门综艺", value: "show-domestic"},
              {title: "热门电影", value: "movie-hot-gaia"},
              {title: "热门电视剧", value: "tv-hot"},
              {title: "电影 TOP250", value: "movie-top250"},
            ],
            cols: 12,
          },
          {
            key: "auto_subscribe_douban_rss_urls",
            label: "自定义 RSS 地址",
            type: "combobox",
            hint: "可输入多个完整 RSS 地址，回车确认。",
            cols: 12,
          },
        ],
      },
      {
        title: "豆瓣订阅筛选",
        icon: "mdi-filter-outline",
        tab: "douban",
        hint: "以下条件同时生效；不满足媒体类型、年份或评分要求的条目不会创建订阅。",
        fields: [
          {key: "auto_subscribe_douban_min_vote", label: "评分≥", type: "number", min: 0, max: 10, cols: 4},
          {key: "auto_subscribe_douban_min_year", label: "年份≥", type: "number", min: 0, cols: 4},
          {
            key: "auto_subscribe_douban_media_type",
            label: "媒体类型",
            type: "select",
            items: [
              {title: "全部", value: "all"},
              {title: "电影", value: "movie"},
              {title: "电视剧", value: "tv"},
            ],
            cols: 4,
          },
        ],
      },
      {
        title: "猫眼连接与测试",
        icon: "mdi-server-network-outline",
        tab: "maoyan",
        fields: [
          {key: "auto_subscribe_maoyan_enabled", label: "启用猫眼榜单", type: "switch", cols: 6},
          {
            key: "auto_subscribe_maoyan_proxy",
            label: "启用代理服务器",
            type: "switch",
            hint: "使用通用设置中的榜单代理。",
            cols: 6,
          },
          {
            key: "auto_subscribe_maoyan_base_url",
            label: "猫眼服务地址",
            hint: "榜单接口服务根地址。",
            cols: 12,
          },
          {
            key: "auto_subscribe_maoyan_test",
            label: "测试猫眼榜单",
            type: "test-auto-subscribe",
            provider: "maoyan",
            cols: 12,
          },
        ],
      },
      {
        title: "猫眼榜单范围",
        icon: "mdi-filmstrip",
        tab: "maoyan",
        hint: "网络电影数据源已停更，不再提供。",
        fields: [
          {key: "auto_subscribe_maoyan_movie_box", label: "电影票房榜", type: "switch", cols: 4},
          {
            key: "auto_subscribe_maoyan_media_type",
            label: "媒体类型",
            type: "select",
            items: [
              {title: "全部", value: "all"},
              {title: "电影", value: "movie"},
              {title: "电视剧", value: "tv"},
            ],
            cols: 8,
          },
          {
            key: "auto_subscribe_maoyan_web_platform_map",
            label: "网播热度 平台 × 类型",
            type: "region-media-map",
            cols: 12,
            items: [
              {title: "全网", value: "all"},
              {title: "腾讯视频", value: "tx"},
              {title: "爱奇艺", value: "iqiyi"},
              {title: "优酷", value: "youku"},
              {title: "乐视", value: "letv"},
              {title: "芒果TV", value: "mgtv"},
              {title: "PPTV", value: "pptv"},
              {title: "搜狐", value: "sohu"},
            ],
            columns: [
              {title: "电视剧+网络剧", value: "series"},
              {title: "电视剧", value: "tv"},
              {title: "网络剧", value: "web"},
              {title: "综艺", value: "variety"},
            ],
            hint: "点击打开配置窗口，按平台分别选择网播类型。",
          },
        ],
      },
      {
        title: "猫眼订阅筛选",
        icon: "mdi-filter-outline",
        tab: "maoyan",
        hint: "以下条件同时生效；不满足年份或评分要求的条目不会创建订阅。",
        fields: [
          {key: "auto_subscribe_maoyan_limit", label: "每榜条数", type: "number", min: 1, max: 100, cols: 4},
          {key: "auto_subscribe_maoyan_min_vote", label: "评分≥", type: "number", min: 0, max: 10, cols: 4},
          {key: "auto_subscribe_maoyan_min_year", label: "年份≥", type: "number", min: 0, cols: 4},
        ],
      },
      {
        title: "Netflix 连接与测试",
        icon: "mdi-server-network-outline",
        tab: "netflix",
        fields: [
          {key: "auto_subscribe_netflix_enabled", label: "启用 Netflix 榜单", type: "switch", cols: 6},
          {
            key: "auto_subscribe_netflix_proxy",
            label: "启用代理服务器",
            type: "switch",
            hint: "使用通用设置中的榜单代理。",
            cols: 6,
          },
          {
            key: "auto_subscribe_netflix_base_url",
            label: "Netflix 服务地址",
            hint: "Tudum 榜单页和 TSV 数据的服务根地址。",
            cols: 12,
          },
          {
            key: "auto_subscribe_netflix_test",
            label: "测试 Netflix 榜单",
            type: "test-auto-subscribe",
            provider: "netflix",
            cols: 12,
          },
        ],
      },
      {
        title: "Netflix 榜单范围",
        icon: "mdi-netflix",
        tab: "netflix",
        fields: [
          {key: "auto_subscribe_netflix_global", label: "全球榜", type: "switch", cols: 4},
          {
            key: "auto_subscribe_netflix_global_dataset",
            label: "全球数据源",
            type: "select",
            items: [
              {title: "最新周榜", value: "weekly"},
              {title: "史上最热（不分周）", value: "popular"},
            ],
            cols: 8,
          },
          {
            key: "auto_subscribe_netflix_global_media_types",
            label: "全球榜媒体类型",
            type: "select",
            multiple: true,
            items: [
              {title: "英语电影", value: "Films (English)"},
              {title: "非英语电影", value: "Films (Non-English)"},
              {title: "英语剧集", value: "TV (English)"},
              {title: "非英语剧集", value: "TV (Non-English)"},
            ],
            hint: "媒体类型使用多选下拉；榜单识别后统一通过 TMDB 取中文标题。",
            cols: 12,
          },
          {
            key: "auto_subscribe_netflix_country_selections",
            label: "国家/地区 × 媒体类型",
            type: "region-media-map",
            cols: 12,
            items: netflixCountryItems,
            columns: [
              {title: "电影", value: "Films"},
              {title: "剧集", value: "TV"},
            ],
            hint: "点击打开配置窗口，按地区分别选择媒体类型。",
          },
        ],
      },
      {
        title: "Netflix 订阅筛选",
        icon: "mdi-filter-outline",
        tab: "netflix",
        hint: "以下条件同时生效；不满足年份或评分要求的条目不会创建订阅。",
        fields: [
          {key: "auto_subscribe_netflix_limit", label: "每榜取前 N", type: "number", min: 1, max: 100, cols: 4},
          {key: "auto_subscribe_netflix_min_vote", label: "评分≥", type: "number", min: 0, max: 10, cols: 4},
          {key: "auto_subscribe_netflix_min_year", label: "年份≥", type: "number", min: 0, cols: 4},
        ],
      },
      {
        title: "Netflix 识别与缓存",
        icon: "mdi-database-sync-outline",
        tab: "netflix",
        fields: [
          {
            key: "auto_subscribe_netflix_rich_metadata",
            label: "抓取详细元数据",
            type: "switch",
            hint: "抓 Tudum 榜单页补充年份和干净剧名，识别更准但更慢。",
            cols: 4,
          },
          {
            key: "auto_subscribe_netflix_max_workers",
            label: "元数据并发数",
            type: "number",
            min: 1,
            max: 16,
            cols: 4,
          },
          {
            key: "auto_subscribe_netflix_use_cache",
            label: "启用周更缓存",
            type: "switch",
            hint: "同一榜单周内避免重复抓取。",
            cols: 4,
          },
        ],
      },
      {
        title: "Mikan 连接与测试",
        icon: "mdi-server-network-outline",
        tab: "mikan",
        fields: [
          {key: "auto_subscribe_mikan_enabled", label: "启用 Mikan 新番", type: "switch", cols: 4},
          {
            key: "auto_subscribe_mikan_proxy",
            label: "启用代理服务器",
            type: "switch",
            hint: "使用通用设置中的榜单代理。",
            cols: 4,
          },
          {
            key: "auto_subscribe_mikan_resolve_bangumi_id",
            label: "抓取 Bangumi ID",
            type: "switch",
            hint: "访问番组详情补充 Bangumi ID 和放送年份，识别更准但请求更慢。",
            cols: 4,
          },
          {
            key: "auto_subscribe_mikan_base_urls",
            label: "Mikan 服务地址",
            type: "combobox",
            multiple: true,
            items: [
              {title: "mikanani.me", value: "https://mikanani.me"},
              {title: "mikanime.tv", value: "https://mikanime.tv"},
            ],
            hint: "可选择或输入多个服务根地址，按顺序尝试。",
            cols: 12,
          },
          {
            key: "auto_subscribe_mikan_test",
            label: "测试 Mikan 新番",
            type: "test-auto-subscribe",
            provider: "mikan",
            cols: 12,
          },
        ],
      },
      {
        title: "Mikan 榜单范围",
        icon: "mdi-animation-outline",
        tab: "mikan",
        fields: [
          {key: "auto_subscribe_mikan_year", label: "番组年份", type: "number", min: 0, cols: 6},
          {
            key: "auto_subscribe_mikan_season",
            label: "季度",
            type: "select",
            items: [
              {title: "当前季度（自动）", value: "当前"},
              {title: "春季", value: "春"},
              {title: "夏季", value: "夏"},
              {title: "秋季", value: "秋"},
              {title: "冬季", value: "冬"},
            ],
            cols: 6,
          },
        ],
      },
      {
        title: "Mikan 订阅筛选",
        icon: "mdi-filter-outline",
        tab: "mikan",
        hint: "以下条件同时生效；不满足年份或评分要求的条目不会创建订阅。",
        fields: [
          {key: "auto_subscribe_mikan_min_vote", label: "评分≥", type: "number", min: 0, max: 10, cols: 6},
          {key: "auto_subscribe_mikan_min_year", label: "年份≥", type: "number", min: 0, cols: 6},
        ],
      },
    ],
  };
}
