import {enabled} from "./helpers.js";

export function createTransferSection(options) {
  return {
    value: "transfer",
    title: "转存设置",
    icon: "mdi-cloud-download-outline",
    groups: [
      {
        title: "订阅范围",
        icon: "mdi-filter-outline",
        fields: [
          {
            key: "subscribe_filter_mode",
            label: "订阅筛选模式",
            type: "select",
            items: [
              { title: "排除所选订阅", value: "exclude" },
              { title: "仅处理所选订阅", value: "include" },
            ],
            cols: 4,
          },
          {
            key: "exclude_subscribes",
            label: "排除订阅",
            type: "select",
            items: options.subscribes,
            multiple: true,
            searchable: true,
            cols: 8,
            show: (config) => config.subscribe_filter_mode === "exclude",
          },
          {
            key: "include_subscribes",
            label: "指定订阅",
            type: "select",
            items: options.subscribes,
            multiple: true,
            searchable: true,
            cols: 8,
            show: (config) => config.subscribe_filter_mode === "include",
          },
        ],
      },
      {
        title: "转存控制",
        icon: "mdi-tune-variant",
        fields: [
          {
            key: "cross_transfer_enabled",
            label: "跨盘资源自动转存",
            type: "switch",
            hint: "目标网盘不一致时尝试秒传或中继转存",
            cols: 4,
          },
          {
            key: "organize_after_transfer",
            label: "转存后自动整理",
            type: "switch",
            hint: "关闭后保留在中转目录，不执行刮削整理",
            cols: 4,
          },
          {
            key: "skip_other_season_dirs",
            label: "跳过其他季目录",
            type: "switch",
            hint: "自动跳过与目标季数不一致的文件",
            cols: 4,
          },
          {
            key: "organize_subtitles",
            label: "整理伴随字幕",
            type: "switch",
            hint: "转存后同步下载与整理匹配字幕",
            cols: 4,
          },
          {
            key: "subtitle_traditional_to_simplified",
            label: "字幕自动繁转简",
            type: "switch",
            hint: "将伴随字幕自动繁转简保存",
            cols: 4,
          },
          {
            key: "anime_pack_preferred",
            label: "动漫优先下载合集",
            type: "switch",
            hint: "存在合集资源时优先选择合集",
            cols: 4,
          },
          {
            key: "offline_timeout",
            label: "离线下载超时（分钟）",
            hint: "超时未完成则标记超时退出，默认 30 分钟",
            type: "number",
            min: 10,
            max: 1440,
            cols: 4,
          },
          {
            key: "cross_transfer_info",
            type: "info",
            label: "跨盘秒传说明",
            lines: [
              "仅当资源链接所属网盘与当前目标网盘不一致时触发；同盘资源继续使用原生分享转存。",
              "115 使用 SHA1；123、光鸭、天翼使用 MD5。只有源文件校验和与目标算法一致时才尝试秒传。",
              "秒传未命中或源端缺少可用校验和时，自动下载到本地缓存并普通上传；成功后清理，失败或取消时保留以便恢复。",
              "任务统一显示在订阅任务中，并区分校验、秒传、源盘下载、目标盘上传、完成、失败和取消状态。",
            ],
            cols: 12,
            show: enabled("cross_transfer_enabled"),
          },
          {
            key: "transfer_task_batch_size",
            label: "任务内每批处理文件数",
            hint: "单批次最大处理文件数",
            type: "number",
            min: 1,
            max: 1000,
            cols: 4,
          },
          {
            key: "subscription_concurrency",
            label: "订阅并发数",
            type: "number",
            min: 1,
            max: 5,
            cols: 4,
          },
          {
            key: "transfer_risk_cooldown",
            label: "转存风控冷却（秒）",
            hint: "触发风控时的休眠等待秒数",
            type: "number",
            min: 60,
            max: 86400,
            cols: 4,
          },
          {
            key: "batch_size",
            label: "分享转存每批数量",
            hint: "单次分享转存文件数",
            type: "number",
            min: 1,
            cols: 4,
          },
          {
            key: "batch_interval",
            label: "转存批次间隔（秒）",
            hint: "连续批次等待间隔",
            type: "number",
            min: 0,
            max: 60,
            cols: 4,
          },
          {
            key: "cross_transfer_download_threads",
            label: "下载线程数",
            type: "number",
            min: 1,
            max: 10,
            cols: 4,
            show: enabled("cross_transfer_enabled"),
          },
          {
            key: "cross_transfer_max_concurrent",
            label: "同时跨盘任务数",
            type: "number",
            min: 1,
            max: 10,
            cols: 4,
            show: enabled("cross_transfer_enabled"),
          },
          {
            key: "cross_transfer_media_types",
            label: "允许跨盘转存类型",
            type: "select",
            items: [
              { title: "电影", value: "movie" },
              { title: "电视剧", value: "tv" },
            ],
            cols: 4,
            multiple: true,
            show: enabled("cross_transfer_enabled"),
          },
        ],
      },
      {
        title: "本地路径与 STRM",
        icon: "mdi-folder-play-outline",
        fields: [
          {
            key: "local_resource_path",
            label: "本地媒体根路径",
            type: "local-directory",
            placeholder: "/strm",
            cols: 6,
          },
          {
            key: "cross_transfer_download_path",
            label: "跨盘中继缓存目录",
            type: "local-directory",
            placeholder: "/tmp",
            default: "/tmp",
            cols: 6,
          },
          {
            key: "strm_generate_enabled",
            label: "转存后直接生成 STRM",
            type: "switch",
            cols: 4,
          },
          {
            key: "nfo_scrape_enabled",
            type: "switch",
            label: "刮削生成 NFO",
            cols: 4,
          },
          {
            key: "image_scrape_enabled",
            type: "switch",
            label: "刮削生成图片",
            cols: 4,
          },
          {
            key: "strm_base_url",
            label: "STRM 基础地址",
            placeholder: "http://172.17.0.1:9527",
            hint: "STRM 播放前缀地址",
            cols: 8,
            show: enabled("strm_generate_enabled"),
          },
          {
            key: "strm_url_template",
            label: "STRM URL 模板",
            type: "textarea",
            hint: "支持 {base_url}、{file_path} 及各网盘 ID 变量",
            cols: 12,
            show: enabled("strm_generate_enabled"),
          },
        ],
      },
    ],
  }
}
